### ISSUE TITLE
Socketio: Join room

### ISSUE THREAD

**Issue by AnthonyHewins** [joshherkness/AR-Top#224] opened 2018-03-07 18:35 UTC

**Comment by nlferman** [comment] 2018-03-09 22:54
Getting a bunch of spammed user connect sessions again.  Sample Message: 

3e2fc703a3a7494daa349a3963a25e85: Upgrade to websocket successful
sockets_1  | 10.0.2.2 - - [09/Mar/2018 22:46:03] "GET /socket.io/?EIO=4&transport=websocket HTTP/1.1" 200 0 0.013124
sockets_1  | (8) accepted ('10.0.2.2', 56557)
sockets_1  | 653c0e4f3ecf437fb7c322fb3ea13910: Sending packet OPEN data {'sid': '653c0e4f3ecf437fb7c322fb3ea13910', 'upgrades': [], 'pingTimeout': 60000, 'pingInterval': 25000}
sockets_1  | emitting event "message" to 653c0e4f3ecf437fb7c322fb3ea13910 [/]
sockets_1  | 653c0e4f3ecf437fb7c322fb3ea13910: Sending packet MESSAGE data 0
sockets_1  | 653c0e4f3ecf437fb7c322fb3ea13910: Received request to upgrade to websocket
sockets_1  | 653c0e4f3ecf437fb7c322fb3ea13910: Sending packet MESSAGE data 2["message","653c0e4f3ecf437fb7c322fb3ea13910 has connected"]

Repeated several times per second.

**Comment by joshherkness** [comment] 2018-03-09 22:58
@goeteeks Not quite sure why this is in here. This thread is about joining a room, not connecting to the server. Is this being caused by #226?

**Comment by joshherkness** [comment] 2018-03-09 23:03
You had it working at one point, right? Try doing a binary search through the commits to figure out which one is the culprit.

**Comment by kdjohnson** [comment] 2018-03-11 14:13
Closed via 63ebcf5

**Closed as completed by kdjohnson** 2018-03-11 14:13 UTC
